{
 "title": "Auctions App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Unhandled exceptions rated[5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(auctions_general_exception_count_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhandled exceptions rated[30m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(auctions_general_exception_count_total[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Login rated[5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(auctions_sessions_login_count_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Login count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "auctions_sessions_login_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Login time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "auctions_sessions_login_time_seconds_max",
     "legendFormat": "__auto"
    },
    {
     "expr": "auctions_sessions_login_time_seconds_sum / auctions_sessions_login_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Logut rated[5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(auctions_sessions_logout_count_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Logout count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "auctions_sessions_logout_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Logout time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "auctions_sessions_logout_time_seconds_max",
     "legendFormat": "__auto"
    },
    {
     "expr": "auctions_sessions_logout_time_seconds_sum / auctions_sessions_logout_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "auctions_sessions_active_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Verify session time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "auctions_sessions_verify_session_time_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}