pipeline {
    agent any
    tools {
        jdk 'jdk-21'
    }

    environment {
        DOCKER_PASSWORD = credentials("docker_password")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Test') {
            steps {
                sh "echo $DOCKER_PASSWORD"
                sh "echo $DOCKER_PASSWORD_PSW"
            }
        }
    }
}
